### ISSUE TITLE
Make Error: expected identifier or '(' before '}' token END_TEST

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-SupportLayer#7]
In file included from testtasksuit.c:5:0:
testtasksuit.c:183:1: error: expected identifier or '(' before '}' token
 END_TEST
 ^
make[6]: *** [/home/john/boat3.1/test/BoAT-ProjectTemplate/build/BoAT-SupportLayer/tests/linux-default/src/osal/testtasksuit.o] Error 1
make[5]: *** [all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [platform] Error 2
make[1]: *** [tests] Error 2
make: *** [test] Error 2

![1685691513664](https://github.com/aitos-io/BoAT-SupportLayer/assets/26243670/172de349-58b5-4c5f-94a5-7eb15178037d)

**Comment by penghaoaitos** [comment]
delete “END_TEST” in testtasksuit.c:183:1.
