### ISSUE TITLE
Make Error: undefined reference to symbol 'floor@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-SupportLayer#8]
./BoAT-SupportLayer/demo/ False
./BoAT-Engine/demo/ True
Configuration completed
config finished
make clean...
make test...
ar: creating /home/john/boat3.1/test/BoAT-ProjectTemplate/lib/libboatvendor.a
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcheck.a(check.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [all] Error 1
make[1]: *** [tests] Error 2
make: *** [test] Error 2
make demo...
ar: creating /home/john/boat3.1/test/BoAT-ProjectTemplate/lib/libboatengine.a

![1685933445841](https://github.com/aitos-io/BoAT-SupportLayer/assets/26243670/dba60c6c-ee87-4daf-b2cd-7e26905fad94)

**Comment by penghaoaitos** [comment]
Download check-0.15.2.tar.gz to properly install libchek dependencies.

https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz
