### ISSUE TITLE
Make Error: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by PanHH** [aitos-io/BoAT-SupportLayer#9]
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [all] Error 1
make[1]: *** [tests] Error 2
make: *** [test] Error 2
make demo...

![1685934878117](https://github.com/aitos-io/BoAT-SupportLayer/assets/26243670/b5b817c5-6bfe-4cee-8343-16cc12a30603)

**Comment by penghaoaitos** [comment]
The automatic Test script failed to compile the boat related library, resulting in link errors.

Clearing the compilation errors of the boat related libraries and successfully compiling the boat libraries libboatvendor. a and libboaengine. a can eliminate the current error.
